MyPrjt1/App1/urls.py
from django.urls import path
from App1.views.company_views import CompanyListView,CompanyDetailView
from App1.views.bank_views import BankListView , BankDetailView
from App1.views.client_views import ClientListView , ClientDetailView
from App1.views.case_stage_views import CaseStageListView , CaseStageDetailView

app_name = 'App1'

urlpatterns = [
    path('company',CompanyListView.as_view(),name='company'),
    path('company_detail/<pk>',CompanyDetailView.as_view(),name='company_detail'),
    path('bank',BankListView.as_view(),name='bank'),
    path('bank_detail/<pk>',BankDetailView.as_view(),name='bank_detail'),
    path('client',ClientListView.as_view(),name='client'),
    path('client_detail/<pk>',ClientDetailView.as_view(),name='client_detail'),
    path('case_stage',CaseStageListView.as_view(),name='case_stage'),
    path('case_stage_detail/<pk>',CaseStageDetailView.as_view(),name='stage_detail'),
]

MyPrjt1/MyPrjt1/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('app1/',include('App1.urls')),
]

MyPrjt1/App1/models.py
from django.db import models

# Create your models here.
class WhoCols(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    created_by =  models.CharField(max_length=200,null=True,blank=True)
    date_updated = models.DateTimeField(auto_now_add=True)
    updated_by =  models.CharField(max_length=200,null=True,blank=True)

    class Meta:
        abstract = True

class Address(models.Model):

    address_line_1 = models.CharField(max_length=200,null=True,blank=True)
    address_line_2 = models.CharField(max_length=200,null=True,blank=True)
    address_line_3 = models.CharField(max_length=200,null=True,blank=True)
    city = models.CharField(max_length=200,null=True,blank=True)
    state = models.CharField(max_length=200,null=True,blank=True)
    pincode = models.CharField(max_length=200,null=True,blank=True)
    country = models.CharField(max_length=200,null=True,blank=True)

    class Meta:
        abstract = True

class Bank(Address,WhoCols):
    bank_name =  models.CharField(max_length=200)
    account_number =  models.IntegerField(unique=True,)
    rtgs_number = models.IntegerField()
    ifsc_code =  models.CharField(max_length=200)

    def __str__(self):
        return self.bank_name
    
    class Meta:
        constraints = [
            models.CheckConstraint(check=models.Q(rtgs_number__gt=0),name='rtgs_number'),
            models.CheckConstraint(check=models.Q(rtgs_number__gt=0),name='account_number')
        ]

class Company(Address,WhoCols):
    company_name =  models.CharField(max_length=200,null=True,blank=True)
    gst_number =  models.CharField(max_length=200,null=True,blank=True)
    registration_number =  models.CharField(max_length=200,null=True,blank=True)
    bank = models.ForeignKey(Bank,on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return self.company_name


class Client(Address,WhoCols):
    client_name =  models.CharField(max_length=200,null=True,blank=True)
    def __str__(self):
        return self.client_name

class Court(Address,WhoCols):
    court_name =  models.CharField(max_length=200,null=True,blank=True)
    def __str__(self):
        return self.court_name

class Stage(WhoCols):
    stage_name =  models.CharField(max_length=200,null=True,blank=True)
    stage_description =  models.CharField(max_length=200,null=True,blank=True)
    def __str__(self):
        return self.stage_name

class Case(WhoCols):
    case_number = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client,on_delete=models.CASCADE)
    description =  models.CharField(max_length=2000,null=True,blank=True)
    court_name =  models.ForeignKey(Court,on_delete=models.CASCADE)
    stage =  models.ForeignKey(Stage,on_delete=models.CASCADE)
    next_date = models.DateTimeField()

    def __str__(self):
        return self.case_number+' - '+self.client+' - '+self.stage

MyPrjt1/App1/forms.py
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS
from .models import Bank,Case,Client,Company,Court 

class BankForm(ModelForm):
    class Meta:
        model = Bank
        fields = ('bank_name','account_number','rtgs_number','ifsc_code'\
             ,'address_line_1','address_line_2','address_line_3','state','city','pincode','country'
             )
        exclude = ('created_by','updated_by')
        

MyPrjt1/App1/views/bank_views.py
from django.shortcuts import render,reverse
from django.views.generic import ListView,DetailView
from App1.models import Bank


class BankListView(ListView):
    template_name = 'generic_list.html'
    model = Bank
    context_object_name = 'object_list'
    extra_context = {'dynamic_url':'App1:bank_detail'}


class BankDetailView(DetailView):
    template_name = 'generic_detail.html'
    model = Bank
    context_object_name = 'object'














# from .base_imports import *

# class BankView(CreateView):
#     template_name = 'bank.html'
#     form_class = BankForm
#     success_url=''
#     def post(self,request,*args,**kwargs):
#         form = self.form_class(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#         else:
#             return render(request,self.template_name,context=self.get_context_data())

MyPrjt1/App1/views/case_stage_views.py
from django.shortcuts import render,reverse
from django.views.generic import ListView,DetailView
from App1.models import Stage


class CaseStageListView(ListView):
    template_name = 'generic_list.html'
    model = Stage
    context_object_name = 'object_list'
    extra_context = {'dynamic_url':'App1:stage_detail'}


class CaseStageDetailView(DetailView):
    template_name = 'generic_detail.html'
    model = Stage
    context_object_name = 'object'

MyPrjt1/App1/views/client_views.py
from django.shortcuts import render,reverse
from django.views.generic import ListView,DetailView
from App1.models import Client
import logging

class ClientListView(ListView):
    template_name = 'generic_list.html'
    model = Client
    context_object_name = 'object_list'
    extra_context = {'dynamic_url':'App1:client_detail'}
    
class ClientDetailView(DetailView):
    template_name = 'generic_detail.html'
    model = Client
    context_object_name = 'object'

MyPrjt1/App1/views/company_views.py
from django.shortcuts import render,reverse
from django.views.generic import ListView , DetailView
from App1.models import Company


class CompanyListView(ListView):
    template_name = 'generic_list.html'
    model = Company
    context_object_name = 'object_list'
    extra_context = {'dynamic_url':'App1:company_detail'}


class CompanyDetailView(DetailView):
    template_name='company_detail.html'
    model = Company
    context_object_name = 'company'

MyPrjt1/MyPrjt1/views.py
from django.shortcuts import render

def index(request):
    return render(request,template_name='index.html')

MyPrjt1/App1/templates/address.html
{% block content %}

<div class="container-fluid">
    <table class="table table-light table-bordered">
        <tbody>
            <tr class="row">
                <td class="col-1">Address Line 1</td>
                <td class="col-3">{{form.address_line_1}}</td>
                <td class="col-1">Address Line 2</td>
                <td class="col-3">{{form.address_line_2}}</td>
                <td class="col-1">Address Line 3</td>
                <td class="col-3">{{form.address_line_3}}</td>
            </tr>
            <tr class="row">
                <td class="col-1">{{form.city.label}}</td>
                <td class="col-2">{{form.city}}</td>
                <td class="col-1">{{form.state.label}}</td>
                <td class="col-2">{{form.state}}</td>
                <td class="col-1">{{form.pincode.label}}</td>
                <td class="col-2">{{form.pincode}}</td>
                <td class="col-1">{{form.country.label}}</td>
                <td class="col-2">{{form.country}}</td>
            </tr>
        </tbody>
    </table>
</div>



{% endblock content %}

MyPrjt1/App1/templates/app1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App-1</title>
</head>
<body>
    <h1>This is from App</h1>
</body>
</html>

MyPrjt1/App1/templates/bank.html
{% extends "address.html" %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{form.bank_name.errors}}
        {{form.errors}}
        <div class="container-fluid">
            <table class="table table table-light">
                <tbody>
                    <tr class="row">
                        <td class="col-2">{{form.bank_name.label}}</td>
                        <td class="col-4">{{form.bank_name}}</td>
                        <td class="col-2">{{form.ifsc_code.label}}</td>
                        <td class="col-4">{{form.ifsc_code}}</td>
                    </tr>
                    <tr class="row">                        
                        <td class="col-2">{{form.account_number.label}}</td>
                        <td class="col-4">{{form.account_number}}<span>{{form.account_number.errors}}</span></td>
                        <td class="col-2">{{form.rtgs_number.label}}</td>
                        <td class="col-4">{{form.rtgs_number}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        {{block.super}}
        
    <input type="submit" value="Save">
    </form>
{% endblock content %}

MyPrjt1/App1/templates/company_detail.html
{% extends "base.html" %}


{% block content %}
{{company.gst_number}}
{{company.key}}

{% include "address.html"  with form=company only %}


{% endblock content %}

MyPrjt1/App1/templates/generic_detail.html
{% extends "base.html" %}

{% block content %}


{% endblock content %}

MyPrjt1/App1/templates/generic_list.html
{% extends "base.html" %}

{% block content %}
<ul class="list-group m-2">
    {% for obj in object_list %}
    <li class="list-group-item ">
        <a href={% url dynamic_url obj.id %}>{{obj}}</a>
    </li>
    {% endfor %}
    
</ul>



{% endblock content %}

MyPrjt1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{{title}}</title>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href=#>Home</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Master Data</a>
                <div class="dropdown-menu" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href={% url "App1:company" %}>Organization</a>
                    <a class="dropdown-item" href={% url "App1:client" %}>Client</a>
                    <a class="dropdown-item" href={% url "App1:bank" %}>Bank</a>
                    <a class="dropdown-item" href={% url "App1:case_stage" %}>Case Stage</a>
                </div>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Case</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Invoice</a>
            </li>
        </ul>
        
    </div>
</nav>
{% block content %}

{% endblock content %}

</body>
</html>

MyPrjt1/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
    <h1 class="display-1">Home Page</h1>
</div>
{% endblock content %}